version: 2.1
orbs:
  maven: circleci/maven@0.0.12
jobs:
   build:
    docker:
      - image: circleci/openjdk:9-jdk
    working_directory: ~/springbootproject-circle-ci-example
    steps:
      - checkout
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: springbootproject-circle-ci-example-{{ checksum “pom.xml” }}
      - run: mvn dependency:go-offline # gets the project dependencies
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: springbootproject-circle-ci-example-{{ checksum “pom.xml” }}
      - run: mvn clean install # run the actual tests
workflows:
  maven_test:
    jobs:
      - build
